"""
Email notification service for Smart DEO
Uses a single Gmail account (with App Password) for all roles.
"""
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Dict
from dotenv import load_dotenv

load_dotenv()

SMTP_HOST     = os.environ.get('SMTP_HOST', 'smtp.gmail.com')
SMTP_PORT     = int(os.environ.get('SMTP_PORT', 587))
SMTP_EMAIL    = os.environ.get('SMTP_EMAIL', '')
SMTP_PASSWORD = os.environ.get('SMTP_APP_PASSWORD', '')

ROLE_DISPLAY = {
    'DEO':   'Data Entry Officer (DEO)',
    'HOD':   'Head of Department (HOD)',
    'Admin': 'System Administrator',
}

INSTITUTION = "Smart DEO — Academic Management System"
FOOTER_NOTE = "This is an official automated communication generated by the Smart DEO Academic Management System. Please do not reply to this email."


def _email_wrapper(content: str, title: str, accent: str = '#1a237e') -> str:
    """Wraps content in a professional email layout."""
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background:#f0f2f5;font-family:'Segoe UI',Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f2f5;padding:30px 0;">
  <tr><td align="center">
    <table width="620" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.08);">

      <!-- Header -->
      <tr>
        <td style="background:linear-gradient(135deg,{accent} 0%,#283593 100%);padding:28px 36px;">
          <table width="100%"><tr>
            <td>
              <div style="font-size:22px;font-weight:700;color:#ffffff;letter-spacing:0.5px;">🎓 Smart DEO</div>
              <div style="font-size:12px;color:rgba(255,255,255,0.75);margin-top:4px;">Academic Management System</div>
            </td>
            <td align="right">
              <div style="background:rgba(255,255,255,0.15);border-radius:6px;padding:6px 14px;display:inline-block;">
                <span style="color:#ffffff;font-size:12px;font-weight:600;">{datetime.now().strftime('%d %b %Y')}</span>
              </div>
            </td>
          </tr></table>
        </td>
      </tr>

      <!-- Title Bar -->
      <tr>
        <td style="background:#e8eaf6;padding:14px 36px;border-bottom:3px solid {accent};">
          <span style="font-size:16px;font-weight:700;color:{accent};">{title}</span>
        </td>
      </tr>

      <!-- Body -->
      <tr>
        <td style="padding:30px 36px;">
          {content}
        </td>
      </tr>

      <!-- Footer -->
      <tr>
        <td style="background:#f8f9fa;padding:20px 36px;border-top:1px solid #e0e0e0;">
          <p style="margin:0;font-size:11px;color:#9e9e9e;line-height:1.6;">{FOOTER_NOTE}</p>
          <p style="margin:8px 0 0;font-size:11px;color:#bdbdbd;">© {datetime.now().year} {INSTITUTION}</p>
        </td>
      </tr>

    </table>
  </td></tr>
</table>
</body>
</html>"""


def send_email(to_email: str, subject: str, body_html: str,
               body_text: str = None, sender_role: str = 'DEO',
               custom_sender_email: str = None, custom_sender_pw: str = None) -> bool:
    
    sender_user = custom_sender_email or SMTP_EMAIL
    sender_pass = custom_sender_pw or SMTP_PASSWORD

    if not sender_user or not sender_pass:
        print(f"[Email] Sender credentials not set for {sender_role}")
        return False

    from_name = ROLE_DISPLAY.get(sender_role, 'Smart DEO System')

    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From']    = f"{from_name} <{SMTP_EMAIL}>"
        msg['To']      = to_email

        if body_text:
            msg.attach(MIMEText(body_text, 'plain'))
        msg.attach(MIMEText(body_html, 'html'))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=60) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(sender_user, sender_pass)
            server.send_message(msg)
            server.quit()

        print(f"[Email] ✅ Sent to {to_email}: {subject} (from {sender_user})")
        return True

    except smtplib.SMTPAuthenticationError as e:
        print(f"[Email] ❌ Auth failed: {e}")
        return False
    except Exception as e:
        print(f"[Email] ❌ Error: {e}")
        return False


def send_low_attendance_alert(student: Dict, recipient_email: str, sender_role: str = 'DEO') -> bool:
    subject = f"[Smart DEO] Attendance Deficiency Notice — {student['name']} ({student['roll']})"

    att = student.get('attendance', 0)
    att_color = '#c62828' if att < 65 else '#e65100'
    status = 'Critical' if att < 65 else 'Below Minimum Requirement'

    content = f"""
    <p style="font-size:15px;color:#212121;margin:0 0 20px;">Dear Concerned Authority,</p>

    <p style="font-size:14px;color:#424242;line-height:1.7;margin:0 0 20px;">
        This is an official notification to bring to your attention that the following student has recorded
        attendance below the minimum required threshold of <strong>75%</strong>. Immediate academic intervention
        is recommended to prevent further academic consequences.
    </p>

    <!-- Student Info Box -->
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#fff8e1;border:1px solid #ffe082;border-left:5px solid #f9a825;border-radius:6px;margin-bottom:24px;">
      <tr><td style="padding:20px 24px;">
        <div style="font-size:13px;font-weight:700;color:#f57f17;text-transform:uppercase;letter-spacing:0.8px;margin-bottom:14px;">Student Details</div>
        <table width="100%" cellpadding="6" cellspacing="0" style="font-size:13px;color:#424242;">
          <tr><td width="40%" style="color:#757575;">Full Name</td><td><strong>{student['name']}</strong></td></tr>
          <tr><td style="color:#757575;">Roll Number</td><td><strong>{student['roll']}</strong></td></tr>
          <tr><td style="color:#757575;">Section</td><td><strong>{student.get('section','N/A')}</strong></td></tr>
          <tr><td style="color:#757575;">Department</td><td><strong>{student.get('department','CSE')}</strong></td></tr>
          <tr><td style="color:#757575;">Current CGPA</td><td><strong>{student.get('cgpa', 0)}</strong></td></tr>
          <tr><td style="color:#757575;">Backlogs</td><td><strong>{student.get('backlogs', 0)}</strong></td></tr>
        </table>
      </td></tr>
    </table>

    <!-- Attendance Alert Box -->
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#ffebee;border:1px solid #ef9a9a;border-left:5px solid {att_color};border-radius:6px;margin-bottom:24px;">
      <tr><td style="padding:20px 24px;">
        <div style="font-size:13px;font-weight:700;color:{att_color};text-transform:uppercase;letter-spacing:0.8px;margin-bottom:10px;">Attendance Status — {status}</div>
        <table width="100%" cellpadding="6" cellspacing="0" style="font-size:13px;">
          <tr>
            <td style="color:#757575;">Current Attendance</td>
            <td><strong style="font-size:22px;color:{att_color};">{att}%</strong></td>
          </tr>
          <tr>
            <td style="color:#757575;">Minimum Required</td>
            <td><strong>75%</strong></td>
          </tr>
          <tr>
            <td style="color:#757575;">Shortfall</td>
            <td><strong style="color:{att_color};">{max(0, 75 - att)}%</strong></td>
          </tr>
        </table>
      </td></tr>
    </table>

    <!-- Action Required -->
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#e8f5e9;border:1px solid #a5d6a7;border-left:5px solid #2e7d32;border-radius:6px;margin-bottom:24px;">
      <tr><td style="padding:18px 24px;">
        <div style="font-size:13px;font-weight:700;color:#1b5e20;text-transform:uppercase;letter-spacing:0.8px;margin-bottom:10px;">Recommended Actions</div>
        <ul style="margin:0;padding-left:18px;font-size:13px;color:#2e7d32;line-height:2;">
          <li>Counsel the student regarding attendance policy and academic implications</li>
          <li>Notify the student's parent or guardian if necessary</li>
          <li>Monitor attendance closely in subsequent sessions</li>
          <li>Consider issuing a formal attendance warning letter</li>
        </ul>
      </td></tr>
    </table>

    <p style="font-size:13px;color:#616161;line-height:1.7;">
        This notification was generated by the <strong>Smart DEO Academic Management System</strong>
        on <strong>{datetime.now().strftime('%B %d, %Y at %I:%M %p')}</strong>.
        Issued by: <strong>{ROLE_DISPLAY.get(sender_role, sender_role)}</strong>.
    </p>
    """

    html = _email_wrapper(content, "⚠️ Attendance Deficiency Notice", accent='#e65100')
    return send_email(recipient_email, subject, html, sender_role=sender_role, 
                      custom_sender_email=student.get('sender_email'),
                      custom_sender_pw=student.get('sender_pw'))


def send_poor_performance_alert(student: Dict, recipient_email: str, sender_role: str = 'DEO') -> bool:
    subject = f"[Smart DEO] Academic Performance Alert — {student['name']} ({student['roll']})"

    cgpa = student.get('cgpa', 0)
    cgpa_color = '#c62828' if cgpa < 5 else '#e65100'
    status = 'Critical — Immediate Intervention Required' if cgpa < 5 else 'Below Satisfactory Level'

    content = f"""
    <p style="font-size:15px;color:#212121;margin:0 0 20px;">Dear Concerned Authority,</p>

    <p style="font-size:14px;color:#424242;line-height:1.7;margin:0 0 20px;">
        This is an official academic performance alert issued by the Smart DEO system. The student listed below
        has demonstrated academic performance that falls below the institution's satisfactory standards.
        Prompt academic support and counseling are strongly advised.
    </p>

    <!-- Student Info Box -->
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#fce4ec;border:1px solid #f48fb1;border-left:5px solid #c62828;border-radius:6px;margin-bottom:24px;">
      <tr><td style="padding:20px 24px;">
        <div style="font-size:13px;font-weight:700;color:#b71c1c;text-transform:uppercase;letter-spacing:0.8px;margin-bottom:14px;">Student Academic Profile</div>
        <table width="100%" cellpadding="6" cellspacing="0" style="font-size:13px;color:#424242;">
          <tr><td width="40%" style="color:#757575;">Full Name</td><td><strong>{student['name']}</strong></td></tr>
          <tr><td style="color:#757575;">Roll Number</td><td><strong>{student['roll']}</strong></td></tr>
          <tr><td style="color:#757575;">Section</td><td><strong>{student.get('section','N/A')}</strong></td></tr>
          <tr><td style="color:#757575;">Department</td><td><strong>{student.get('department','CSE')}</strong></td></tr>
          <tr><td style="color:#757575;">Attendance</td><td><strong>{student.get('attendance',0)}%</strong></td></tr>
          <tr><td style="color:#757575;">Internal Marks</td><td><strong>{student.get('internal',0)} / 50</strong></td></tr>
          <tr><td style="color:#757575;">External Marks</td><td><strong>{student.get('external',0)} / 100</strong></td></tr>
          <tr><td style="color:#757575;">Active Backlogs</td><td><strong style="color:#c62828;">{student.get('backlogs',0)}</strong></td></tr>
        </table>
      </td></tr>
    </table>

    <!-- CGPA Alert -->
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#ffebee;border:1px solid #ef9a9a;border-left:5px solid {cgpa_color};border-radius:6px;margin-bottom:24px;">
      <tr><td style="padding:20px 24px;">
        <div style="font-size:13px;font-weight:700;color:{cgpa_color};text-transform:uppercase;letter-spacing:0.8px;margin-bottom:10px;">Performance Status — {status}</div>
        <table width="100%" cellpadding="6" cellspacing="0" style="font-size:13px;">
          <tr>
            <td style="color:#757575;">Current CGPA</td>
            <td><strong style="font-size:26px;color:{cgpa_color};">{cgpa}</strong> <span style="color:#9e9e9e;font-size:13px;">/ 10.0</span></td>
          </tr>
          <tr><td style="color:#757575;">Minimum Satisfactory</td><td><strong>6.0</strong></td></tr>
        </table>
      </td></tr>
    </table>

    <!-- Action Required -->
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#e8f5e9;border:1px solid #a5d6a7;border-left:5px solid #2e7d32;border-radius:6px;margin-bottom:24px;">
      <tr><td style="padding:18px 24px;">
        <div style="font-size:13px;font-weight:700;color:#1b5e20;text-transform:uppercase;letter-spacing:0.8px;margin-bottom:10px;">Recommended Actions</div>
        <ul style="margin:0;padding-left:18px;font-size:13px;color:#2e7d32;line-height:2;">
          <li>Schedule an academic counseling session with the student</li>
          <li>Review subject-wise performance and identify weak areas</li>
          <li>Provide additional academic support or remedial classes</li>
          <li>Coordinate with subject faculty for targeted improvement plans</li>
          <li>Inform parent or guardian of current academic standing</li>
        </ul>
      </td></tr>
    </table>

    <p style="font-size:13px;color:#616161;line-height:1.7;">
        This notification was generated by the <strong>Smart DEO Academic Management System</strong>
        on <strong>{datetime.now().strftime('%B %d, %Y at %I:%M %p')}</strong>.
        Issued by: <strong>{ROLE_DISPLAY.get(sender_role, sender_role)}</strong>.
    </p>
    """

    html = _email_wrapper(content, "📉 Academic Performance Alert", accent='#b71c1c')
    return send_email(recipient_email, subject, html, sender_role=sender_role,
                      custom_sender_email=student.get('sender_email'),
                      custom_sender_pw=student.get('sender_pw'))


def send_bulk_report(recipient_email: str, report_data: Dict, sender_role: str = 'DEO') -> bool:
    subject = f"[Smart DEO] Departmental Academic Performance Report — {datetime.now().strftime('%B %Y')}"

    total    = report_data.get('total_students', 0)
    avg_cgpa = report_data.get('avg_cgpa', 0)
    avg_att  = report_data.get('avg_attendance', 0)
    low_att  = report_data.get('low_attendance', 0)
    at_risk  = report_data.get('at_risk', 0)
    backlogs = report_data.get('with_backlogs', 0)
    att_pct  = round((total - low_att) / total * 100, 1) if total else 0
    risk_pct = round(at_risk / total * 100, 1) if total else 0

    content = f"""
    <p style="font-size:15px;color:#212121;margin:0 0 16px;">Dear Concerned Authority,</p>
    <p style="font-size:14px;color:#424242;line-height:1.7;margin:0 0 20px;">
        Please find below the consolidated academic performance report for <strong>{datetime.now().strftime('%B %Y')}</strong>,
        automatically generated by the Smart DEO Academic Management System.
    </p>

    <table width="100%" cellpadding="10" cellspacing="0" style="background:#e8eaf6;border-left:5px solid #1a237e;border-radius:6px;margin-bottom:18px;font-size:13px;color:#424242;">
      <tr><td colspan="2" style="font-weight:700;color:#1a237e;font-size:13px;text-transform:uppercase;letter-spacing:0.8px;padding-bottom:6px;">📊 Overall Statistics</td></tr>
      <tr style="background:rgba(255,255,255,0.6);"><td>Total Enrolled Students</td><td><strong>{total}</strong></td></tr>
      <tr><td>Department Average CGPA</td><td><strong>{avg_cgpa}</strong></td></tr>
      <tr style="background:rgba(255,255,255,0.6);"><td>Department Average Attendance</td><td><strong>{avg_att}%</strong></td></tr>
      <tr><td>Students with Adequate Attendance (≥75%)</td><td><strong style="color:#2e7d32;">{total - low_att} ({att_pct}%)</strong></td></tr>
    </table>

    <table width="100%" cellpadding="10" cellspacing="0" style="background:#fff8e1;border-left:5px solid #f9a825;border-radius:6px;margin-bottom:18px;font-size:13px;color:#424242;">
      <tr><td colspan="2" style="font-weight:700;color:#f57f17;font-size:13px;text-transform:uppercase;letter-spacing:0.8px;padding-bottom:6px;">⚠️ Risk Indicators</td></tr>
      <tr style="background:rgba(255,255,255,0.6);"><td>Students with Low Attendance (&lt;75%)</td><td><strong style="color:#c62828;">{low_att}</strong></td></tr>
      <tr><td>Students at Academic Risk</td><td><strong style="color:#e65100;">{at_risk} ({risk_pct}%)</strong></td></tr>
      <tr style="background:rgba(255,255,255,0.6);"><td>Students with Active Backlogs</td><td><strong style="color:#c62828;">{backlogs}</strong></td></tr>
    </table>

    <table width="100%" cellpadding="10" cellspacing="0" style="background:#e8f5e9;border-left:5px solid #2e7d32;border-radius:6px;margin-bottom:20px;font-size:13px;color:#2e7d32;">
      <tr><td style="font-weight:700;color:#1b5e20;font-size:13px;text-transform:uppercase;letter-spacing:0.8px;padding-bottom:6px;">📋 Recommendations</td></tr>
      <tr><td>• Initiate counseling for all at-risk students identified above<br>
               • Issue formal attendance notices to students below 75% threshold<br>
               • Coordinate with faculty for remedial support for backlog students<br>
               • Schedule parent-teacher meetings for critical cases</td></tr>
    </table>

    <p style="font-size:13px;color:#616161;line-height:1.7;">
        Report generated on <strong>{datetime.now().strftime('%B %d, %Y at %I:%M %p')}</strong>.
        Issued by: <strong>{ROLE_DISPLAY.get(sender_role, sender_role)}</strong>.
        For detailed student-level data, please log in to the Smart DEO portal.
    </p>
    """

    html = _email_wrapper(content, f"📊 Departmental Performance Report — {datetime.now().strftime('%B %Y')}", accent='#1a237e')
    return send_email(recipient_email, subject, html, sender_role=sender_role)
